### ISSUE TITLE
Fails to build on Mac OSX for 0.5.0

### ISSUE THREAD

**Issue by metaphorz** [leopard86/LOGinstruments#5]
I wasn't clear whether "git updates > 0.4.0" meant 0.5.0 ? The last commit was about 3 days ago, so it seemed a reasonable guess. But if that is so, there are problems with an OSX build. The main one is an error (there are 6 of them) having to do with overloading "=". The warnings are related to a "converted initializer". Here is a partial dump:

In file included from src/LOGinstruments.cpp:1:
In file included from src/LOGinstruments.hpp:1:
../../include/rack.hpp:34:14: error: no viable overloaded '='
        model->tags = {tags...};
        ~~~~~~~~~~~ ^ ~~~~~~~~~
src/LOGinstruments.cpp:18:14: note: in instantiation of function template
      specialization 'rack::createModel<VelvetWidget, const char *, rack::ModelTag>'
      requested here
        p->addModel(createModel<VelvetWidget>("LOGinstruments", "LOGinstrument...
                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/list:862:11: note: 
      candidate function not viable: cannot convert initializer list argument to
      'const std::__1::list<rack::ModelTag, std::__1::allocator<rack::ModelTag> >'
    list& operator=(const list& __c);
          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/list:874:11: note: 
      candidate function not viable: cannot convert initializer list argument to
      'std::__1::list<rack::ModelTag, std::__1::allocator<rack::ModelTag> >'
    list& operator=(list&& __c)
          ^

**Comment by LOGUNIVPM** [comment]
Thanks, at the moment the version that is available on git is not up to date with 0.5.0.
It will be soon, then I'll make a new post here and close the thread.

**Comment by LOGUNIVPM** [comment]
Now it is ready for 0.5.0
